name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build Docker images
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          outputs: "type=image"
          platforms: linux/amd64,linux/arm64
          push: false
          tags: step-security/terraform-docs

      - name: Should generate USAGE.md for tf11_basic
        uses: ./
        with:
          working-dir: examples/tf11_basic
          output-file: USAGE.md
          template: |-
            <!-- BEGIN_TF_DOCS -->
            # Test tf11 basic

            ## Verify

            Should use the template defined instead of the default
            Should inject the table under usage

            # Usage

            {{ .Content }}
            <!-- END_TF_DOCS -->
          indention: 3

      - name: Should generate USAGE.md for tf11_extra_args
        uses: ./
        with:
          working-dir: examples/tf11_extra_args
          output-format: markdown document
          output-file: USAGE.md
          output-method: replace
          args: --sensitive=false --hide requirements --required=false
          indention: 3

      - name: Should generate README.md for tf12_bsic
        uses: ./
        with:
          working-dir: examples/tf12_basic
          indention: 3

      - name: Should generate README.md for tf12_atlantis
        uses: ./
        with:
          atlantis-file: atlantis.yaml
          args: --hide providers
          indention: 3

      - name: Should generate USAGE.md for tf12_find and its submodules
        uses: ./
        with:
          find-dir: examples/tf12_find
          output-file: USAGE.md

      - name: Should generate USAGE.md for tf12_find and its submodules recursively
        uses: ./
        with:
          working-dir: examples/tf12_find
          output-file: USAGE.md
          recursive: true
          recursive-path: modules

      - name: Should generate README.md for tf12_config
        uses: ./
        with:
          working-dir: examples/tf12_config
          config-file: .terraform-docs.yml

      - name: Should generate README.md for tf12_inject and push up all changes
        uses: ./
        with:
          working-dir: examples/tf12_inject
          args: --sort-by required
          indention: 3
          git-push: true
          git-push-sign-off: true
          git-commit-message: "terraform-docs: automated action"

      - name: Should generate README.md for tf12_fail_diff and fail on diff
        continue-on-error: true
        uses: ./
        with:
          working-dir: examples/tf12_fail_diff
          indention: 3
          fail-on-diff: true

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Terraform format
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '0.12.17'

      - run: terraform fmt examples
